### ISSUE TITLE
登录相关咨询，谢谢赐教

### ISSUE THREAD

**Issue by pullwindyuan** [EwingTsai/spring-boot-faster#1]
你好，我现在在使用你的项目，但是我们找不到你的login接口在哪里实现的，应为我想修改登录相关的流程，能否赐教。我需要加入token验证的方式登录，但是我不知道目前你的登录鉴权方面的东西是在哪里做的？看介绍你使用的是spring security

**Comment by EwingTsai** [comment]
参考 ewing.security.WebSecurityConfig，具体怎么做你需要先学习 Spring Security 才行
